### PR TITLE
Discover filters

### PR DESCRIPTION
**Pull request by nsadakuni**
- Main Discover component maps interest categories and calls RenderInterests for each
- New component RenderInterests
- Basic functionality to render categorized interests and conditionally render specific interests per category onPress

### CODE REVIEW

**Review by Benjamin-Cardon — APPROVED** [review]
You've already done a great job pumping out this code. Only thing I'd have suggested be done different is passing the interests object as a prop, so refactor would be a little simpler. Not a big critique- easy approve.

**Comment by Benjamin-Cardon** [comment]
Actually ignore previous comment- I missed the point that interests might be the kind of thing we might have to get asynchronously or would be static anyway.

**Comment by nsadakuni** [comment]
Hmm can you expand on what you mean here? I am currently passing each individual interest category with its associated items as a prop to the RenderInterest components (see line 31 of discover/index.jsx)

**Comment by Benjamin-Cardon** [comment]
**I** was confused. There wasn't actually anything wrong with how you did it.  What I didn't understand was why the whole "Interests Array" wasn't being passed as a prop to the Discover Component. 
However, Interests isn't a dynamic property necessarily, so It shouldn't be a prop. Either it's something which would be in the cloud database, or it's something which would be hardcoded. The way you had done things didn't actually have a problem with it.

**Pull request merged**
